import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import { fetchTenantById } from "@/lib/data";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout(pageProps) {
  const tenant = pageProps.params.tenant;
  let tenantName = "Unknown";
  const selection = await fetchTenantById(tenant);
  tenantName = selection?.name ?? tenantName;
  const tenantID = selection?.id;
  return (
    <div className="h-full bg-gray-100" suppressHydrationWarning={true}>
      <Navigation tenantID={tenantID} tenant={tenantName}>
        {pageProps.children}
      </Navigation>
    </div>
  );
}
