import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div className="h-full bg-gray-100" suppressHydrationWarning={true}>
      <Navigation>{children}</Navigation>
    </div>
  );
}
